[env:esp32s3]
platform = espressif32
; 建议使用这个通用的 S3 板型配置，它对 N16R8 兼容性较好
board = esp32-s3-devkitc-1
framework = arduino

; --- 核心硬件配置（针对 N16R8 极致性能） ---
; 开启 16MB Flash 支持
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi ; 必须设置，qio 对应 Flash，opi 对应 PSRAM
board_build.f_flash = 80000000L           ; Flash 频率 80MHz
board_build.flash_mode = qio              ; Flash 模式

lib_deps =
    Adafruit LIS2DW12    ; 去掉作者前缀和版本限制，让 PIO 自动抓取最新版
    Adafruit BusIO
    Wire

; --- 串口调试配置 ---
monitor_speed = 115200
monitor_filters = esp32_exception_decoder ; 报错时自动解析代码行号，Debug 神器

; --- 编译优化 ---
build_flags = 
    -D CORE_DEBUG_LEVEL=3                ; 开启 Info 级别的日志输出
    -D BOARD_HAS_PSRAM                   ; 强制开启 PSRAM 支持
    -mfix-esp32-psram-cache-issue
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1  ; 这一行最关键，确保上电即开启串口